/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PolaroidRouteImport } from './routes/polaroid'
import { Route as PhotoboothRouteImport } from './routes/photobooth'
import { Route as DigicamRouteImport } from './routes/digicam'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const PolaroidRoute = PolaroidRouteImport.update({
  id: '/polaroid',
  path: '/polaroid',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoboothRoute = PhotoboothRouteImport.update({
  id: '/photobooth',
  path: '/photobooth',
  getParentRoute: () => rootRouteImport,
} as any)
const DigicamRoute = DigicamRouteImport.update({
  id: '/digicam',
  path: '/digicam',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/digicam': typeof DigicamRoute
  '/photobooth': typeof PhotoboothRoute
  '/polaroid': typeof PolaroidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/digicam': typeof DigicamRoute
  '/photobooth': typeof PhotoboothRoute
  '/polaroid': typeof PolaroidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/digicam': typeof DigicamRoute
  '/photobooth': typeof PhotoboothRoute
  '/polaroid': typeof PolaroidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/digicam' | '/photobooth' | '/polaroid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/digicam' | '/photobooth' | '/polaroid'
  id: '__root__' | '/' | '/calendar' | '/digicam' | '/photobooth' | '/polaroid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DigicamRoute: typeof DigicamRoute
  PhotoboothRoute: typeof PhotoboothRoute
  PolaroidRoute: typeof PolaroidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/polaroid': {
      id: '/polaroid'
      path: '/polaroid'
      fullPath: '/polaroid'
      preLoaderRoute: typeof PolaroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photobooth': {
      id: '/photobooth'
      path: '/photobooth'
      fullPath: '/photobooth'
      preLoaderRoute: typeof PhotoboothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digicam': {
      id: '/digicam'
      path: '/digicam'
      fullPath: '/digicam'
      preLoaderRoute: typeof DigicamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DigicamRoute: DigicamRoute,
  PhotoboothRoute: PhotoboothRoute,
  PolaroidRoute: PolaroidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
